//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.Methods
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class Samples { }
#else

	public class Samples : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public Samples()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/NumericalMethods-Silverlight;component/SampleData/Methods/Methods.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private CategoryCollection _CategoryCollection = new CategoryCollection();

		public CategoryCollection CategoryCollection
		{
			get
			{
				return this._CategoryCollection;
			}
		}
	}

	public class Category : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Title = string.Empty;

		public string Title
		{
			get
			{
				return this._Title;
			}

			set
			{
				if (this._Title != value)
				{
					this._Title = value;
					this.OnPropertyChanged("Title");
				}
			}
		}

		private SampleCollection _SampleCollection = new SampleCollection();

		public SampleCollection SampleCollection
		{
			get
			{
				return this._SampleCollection;
			}
		}
	}

	public class Sample : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Title = string.Empty;

		public string Title
		{
			get
			{
				return this._Title;
			}

			set
			{
				if (this._Title != value)
				{
					this._Title = value;
					this.OnPropertyChanged("Title");
				}
			}
		}

		private string _src = string.Empty;

		public string src
		{
			get
			{
				return this._src;
			}

			set
			{
				if (this._src != value)
				{
					this._src = value;
					this.OnPropertyChanged("src");
				}
			}
		}

		private Syntax _Syntax = new Syntax();

		public Syntax Syntax
		{
			get
			{
				return this._Syntax;
			}

			set
			{
				if (this._Syntax != value)
				{
					this._Syntax = value;
					this.OnPropertyChanged("Syntax");
				}
			}
		}
	}

	public class Syntax : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	public class CategoryCollection : System.Collections.ObjectModel.ObservableCollection<Category>
	{ 
	}

	public class SampleCollection : System.Collections.ObjectModel.ObservableCollection<Sample>
	{ 
	}
#endif
}
